In [6]:
import numpy as np

D = np.asarray([[0, -1], [1, 2]], dtype=np.float)
print(D)
print(abs(D))

[[ 0. -1.]
 [ 1.  2.]]
[[0. 1.]
 [1. 2.]]


In [4]:
for i in range(D.shape[0]):
    for j in range(D.shape[1]):
        if D[i][j] != 0:
            print(D[i][j])
            D[i][j] = np.power(D[i][j], -0.5)
            print(D[i][j])
print(D)

2.8094944872101946e-22
59660365252.489975
1.3673212213428984e-12
855194.1528939068
2.412195354535009e-25
2036074953943.7378
[[0.00000000e+00 5.96603653e+10]
 [8.55194153e+05 2.03607495e+12]]


In [3]:
a = np.power(4, -0.5)
print(a)

0.5
